import nextVitals from "eslint-config-next/core-web-vitals";
import tseslint from "typescript-eslint";
import unknownParseBoundary from "./eslint-rules/unknown-parse-boundary.mjs";

/**
 * Vendored UI. `components/ui` is shadcn output, regenerated by its CLI, which
 * reverts any edit made to satisfy a rule — so it is exempt from the
 * type-safety rules for the same reason `.prettierignore` skips it.
 *
 * `components/ai-elements` is not linted at all (see `ignores` below): the same
 * CLI-output argument applies, and it is outside the TypeScript program, so the
 * type-aware rules have no types to work from.
 */
const VENDORED = ["components/ui/**"];

/** The code this repo owns and holds to constraint C1. */
const OWNED = [
  "app/**/*.{ts,tsx}",
  "components/**/*.{ts,tsx}",
  "db/**/*.ts",
  "hooks/**/*.ts",
  "lib/**/*.ts",
  "server/**/*.ts",
  "store/**/*.ts",
];

export default [
  // Global ignores. Must be an object with no other keys — a config that also
  // carries `rules` would only ignore these files for its own block.
  {
    ignores: [
      ".next/**",
      "out/**",
      "build/**",
      "node_modules/**",
      "next-env.d.ts",
      // AI Elements output, excluded from `tsconfig.json` as well. Phase E
      // deletes 44 of its 48 files.
      "components/ai-elements/**",
    ],
  },

  ...nextVitals,
  {
    rules: {
      "no-console": "off",
      "react/no-children-prop": "off",
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/purity": "off",
      "react-hooks/immutability": "off",
      "react-hooks/static-components": "off",
      "@next/next/no-img-element": "off",
      "import/no-anonymous-default-export": "off",
    },
  },

  // Type-aware linting. `projectService` gives every rule below the real type
  // of every expression, which is what makes the `no-unsafe-*` family able to
  // see an `any` arriving from a dependency's types.
  {
    files: ["**/*.{ts,tsx,mts}"],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: { "@typescript-eslint": tseslint.plugin },
    rules: {
      // No `any`, however it arrives: written by us, or leaked from a
      // dependency's types into an argument, assignment, call or return.
      "no-restricted-syntax": [
        "error",
        {
          selector: "TSAnyKeyword",
          message: "Do not use explicit `any`. Validate or narrow from `unknown` instead.",
        },
      ],
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-return": "error",

      // Illegal states, made unrepresentable: no escape hatches out of the
      // type system, and every union switch handled.
      "@typescript-eslint/consistent-type-assertions": ["error", { assertionStyle: "never" }],
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/switch-exhaustiveness-check": [
        "error",
        { considerDefaultExhaustiveForUnions: true },
      ],

      // Promises: an unawaited one loses its rejection, and one passed where a
      // sync callback is expected is never awaited at all.
      // `test()` from `node:test` returns a promise the runner owns; nothing
      // is lost by not awaiting it, and the tests read better without `void`.
      "@typescript-eslint/no-floating-promises": [
        "error",
        {
          allowForKnownSafeCalls: [
            { from: "package", package: "node:test", name: ["describe", "it", "test"] },
          ],
        },
      ],
      "@typescript-eslint/no-misused-promises": "error",
    },
  },

  // Constraint C1's `unknown` containment, on the code this repo owns.
  {
    files: OWNED,
    ignores: VENDORED,
    plugins: { local: unknownParseBoundary },
    rules: {
      "local/parse-boundary-only": "error",
    },
  },

  // Server-owned code must log through the structured logger wrapper.
  {
    files: ["server/**/*.ts", "app/api/**/*.ts", "lib/**/*.ts", "db/**/*.ts"],
    rules: {
      "no-console": "error",
    },
  },

  // Vendored output: exempt from the rules whose fixes a regeneration would
  // discard. Still linted for correctness by the Next.js rules above.
  {
    files: VENDORED,
    rules: {
      "no-restricted-syntax": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/consistent-type-assertions": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/switch-exhaustiveness-check": "off",
      "@typescript-eslint/no-floating-promises": "off",
      "@typescript-eslint/no-misused-promises": "off",
    },
  },
];
