onlyBuiltDependencies:
  - esbuild
  - msw
overrides:
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  bufferutil: set this to true or false
  core-js: set this to true or false
  esbuild: true
  msw: true
  sharp: false
  unrs-resolver: false
  utf-8-validate: set this to true or false
