onlyBuiltDependencies:
  - esbuild
  - msw
overrides:
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  esbuild: true
  msw: true
  sharp: false
  unrs-resolver: false
