"use client";

import { useChat } from "@ai-sdk/react";
import type { ChatStatus } from "ai";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { ChatComposer } from "@/components/chat/chat-composer";
import { ChatEmptyState } from "@/components/chat/chat-empty-state";
import { ChatMessageList } from "@/components/chat/chat-message-list";
import { useChatViewport } from "@/components/chat/hooks/use-chat-viewport";
import { useChatVisibleStatus } from "@/components/chat/hooks/use-chat-visible-status";
import { chatApi, threadsApi } from "@/lib/api/client";
import type { MessageDto } from "@/lib/api/contracts";
import type { AppUIMessage } from "@/lib/chat/ui-message";
import { convertMessageDtosToUI, mergeEarlierMessages } from "@/lib/converters";
import { THREADS_QUERY_KEY } from "@/lib/query-keys";
import { getChatForThread, useChatStore } from "@/store/chat-store";
import { useQueryClient } from "@tanstack/react-query";
import type { ModelId } from "@/lib/ai/model-registry";

export function ChatShell({
  threadId,
  initialMessages,
  initialNextCursor,
}: {
  /** The thread being viewed. Generated by the server on the home page. */
  threadId: string;
  initialMessages: MessageDto[];
  initialNextCursor: string | null;
}) {
  const { selectedModel } = useChatStore();
  const queryClient = useQueryClient();

  const serverMessages = useMemo(() => convertMessageDtosToUI(initialMessages), [initialMessages]);

  // One instance per thread, seeded once. Nothing here overwrites `messages`
  // afterwards: the shell used to `setMessages(serverMessages)` on every
  // navigation, which raced a running stream and could erase tokens that had
  // already arrived. See `store/chat-store.ts`.
  const chatInstance = useMemo(
    () => getChatForThread(threadId, serverMessages),
    [threadId, serverMessages],
  );

  const { messages, setMessages, sendMessage, status, error, regenerate, stop, clearError } =
    useChat<AppUIMessage>({
      chat: chatInstance,
      // Reattaches to an answer that was still being written when the page was
      // last closed. Answers 204 and does nothing when there is none, which is
      // almost every load.
      resume: true,
    });

  const [nextCursor, setNextCursor] = useState(initialNextCursor);
  const [isLoadingEarlier, setIsLoadingEarlier] = useState(false);
  const [starterPrompt, setStarterPrompt] = useState({ text: "", version: 0 });
  const composerRef = useRef<HTMLDivElement | null>(null);
  const loadingEarlierRef = useRef(false);
  const previousStatusRef = useRef<ChatStatus>(status);

  useChatViewport(composerRef);

  useEffect(() => {
    setNextCursor(initialNextCursor);
  }, [initialNextCursor, threadId]);

  useEffect(() => {
    if (!error) return;
    toast.error(error.message || "Something went wrong", { id: "chat-send-error" });
  }, [error]);

  // A finished turn can have renamed its thread — the title is generated from
  // the first exchange, behind the response — and has certainly changed its
  // ordering in the sidebar. Refetching on the streaming → idle edge is what
  // makes the generated title appear without a reload.
  useEffect(() => {
    const wasStreaming =
      previousStatusRef.current === "streaming" || previousStatusRef.current === "submitted";
    previousStatusRef.current = status;
    if (!wasStreaming || status === "streaming" || status === "submitted") return;
    void queryClient.invalidateQueries({ queryKey: THREADS_QUERY_KEY });
  }, [queryClient, status]);

  const liveStatus: ChatStatus = status;
  const visibleStatus = useChatVisibleStatus({ status: liveStatus, error, messages });
  const isEmpty = messages.length === 0;
  const isNewThread = initialMessages.length === 0 && initialNextCursor === null;

  /**
   * Redoes the last answer, optionally on a different model.
   *
   * `regenerate` re-posts with `regenerate: true`, which tells the server to
   * replace the superseded answer rather than append beside it — in the same
   * transaction that writes the new one, so the thread is never briefly
   * showing two answers to one question.
   */
  const handleRegenerate = useCallback(
    (modelId?: ModelId) => {
      // Nothing to redo. `regenerate()` targets the last message by index and
      // throws on an empty list, which the status bar's Retry could reach after
      // a turn failed before the first message was ever rendered.
      if (messages.length === 0) return;

      clearError();
      void regenerate({
        body: { selectedModel: modelId ?? selectedModel, regenerate: true, attachmentIds: [] },
      });
    },
    [clearError, messages.length, regenerate, selectedModel],
  );

  const handleRetry = useCallback(() => {
    handleRegenerate();
  }, [handleRegenerate]);

  /**
   * Stops the answer, on both sides.
   *
   * The local `stop()` is what makes the UI respond at once; the request is
   * what actually ends the turn, because the server cannot tell an abort from
   * a refresh and must not guess. The local call goes first so the button
   * never feels like it did nothing.
   */
  const handleStop = useCallback(async () => {
    // `stop()` resolves once the local request is torn down; nothing depends on
    // that having finished before the server is told, so it is not awaited.
    void stop();
    try {
      await chatApi.stopStream(threadId);
    } catch (stopError) {
      toast.error(stopError instanceof Error ? stopError.message : "Could not stop the response.");
    }
  }, [stop, threadId]);

  const handlePromptSelect = useCallback((prompt: string) => {
    setStarterPrompt((current) => ({ text: prompt, version: current.version + 1 }));
  }, []);

  const loadEarlier = useCallback(async () => {
    if (
      !nextCursor ||
      loadingEarlierRef.current ||
      status === "submitted" ||
      status === "streaming"
    )
      return;

    loadingEarlierRef.current = true;
    setIsLoadingEarlier(true);
    try {
      const page = await threadsApi.messages(threadId, { cursor: nextCursor, limit: 50 });
      const earlier = convertMessageDtosToUI(page.messages);
      setMessages((current) => mergeEarlierMessages(current, earlier));
      setNextCursor(page.nextCursor);
    } catch (loadError) {
      toast.error(
        loadError instanceof Error ? loadError.message : "Could not load earlier messages",
      );
    } finally {
      loadingEarlierRef.current = false;
      setIsLoadingEarlier(false);
    }
  }, [nextCursor, setMessages, status, threadId]);

  const composer = (
    <ChatComposer
      sendMessage={sendMessage}
      stop={handleStop}
      status={liveStatus}
      visibleStatus={visibleStatus}
      threadId={threadId}
      isNewThread={isNewThread}
      initialInput={starterPrompt.text}
      initialInputVersion={starterPrompt.version}
      containerRef={composerRef}
      onRetry={handleRetry}
    />
  );

  if (isEmpty) {
    return (
      <div className="flex h-dvh min-h-0 flex-1 flex-col overflow-hidden px-2 py-3 [height:var(--chat-viewport-height,100dvh)] sm:px-6 sm:py-5">
        <main className="relative mx-auto flex min-h-0 w-full max-w-5xl flex-1 flex-col items-center justify-end overflow-hidden rounded-[2rem] border border-white/10 bg-zinc-950/35 px-4 pb-0 shadow-[0_28px_120px_-52px_rgba(0,0,0,0.95),inset_0_1px_0_rgba(255,255,255,0.06)] backdrop-blur-2xl md:justify-center md:px-8">
          <div
            className="pointer-events-none absolute inset-x-8 top-0 h-px bg-gradient-to-r from-transparent via-orange-200/45 to-transparent"
            aria-hidden
          />
          <ChatEmptyState onPromptSelect={handlePromptSelect} />
          <div className="w-full">{composer}</div>
        </main>
      </div>
    );
  }

  return (
    <div className="flex h-dvh min-h-0 flex-1 flex-col overflow-hidden px-2 pt-2 [height:var(--chat-viewport-height,100dvh)] sm:px-5 sm:pt-4">
      <main className="relative mx-auto flex min-h-0 w-full max-w-6xl flex-1 flex-col items-center overflow-hidden rounded-t-[2rem] border-x border-t border-white/10 bg-zinc-950/30 shadow-[0_30px_120px_-54px_rgba(0,0,0,0.95),inset_0_1px_0_rgba(255,255,255,0.05)] backdrop-blur-2xl">
        <div
          className="pointer-events-none absolute inset-x-10 top-0 h-px bg-gradient-to-r from-transparent via-orange-200/40 to-transparent"
          aria-hidden
        />
        <section className="flex min-h-0 w-full flex-1 flex-col overflow-hidden">
          <ChatMessageList
            messages={messages}
            status={liveStatus}
            hasEarlierMessages={nextCursor !== null}
            isLoadingEarlier={isLoadingEarlier}
            onLoadEarlier={loadEarlier}
            onRegenerate={handleRegenerate}
          />
          {composer}
        </section>
      </main>
    </div>
  );
}
