"use client";

import { useChat } from "@ai-sdk/react";
import type { ChatStatus } from "ai";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { ChatComposer } from "@/components/chat/chat-composer";
import { ChatEmptyState } from "@/components/chat/chat-empty-state";
import { ChatMessageList } from "@/components/chat/chat-message-list";
import { ChatAnnouncer } from "@/components/chat/chat-announcer";
import { Skeleton } from "@/components/ui/skeleton";
import { useChatViewport } from "@/components/chat/hooks/use-chat-viewport";
import { useChatVisibleStatus } from "@/components/chat/hooks/use-chat-visible-status";
import {
  readCachedWindow,
  TRANSCRIPT_WINDOW_SIZE,
  useThreadTranscript,
} from "@/components/chat/hooks/use-thread-transcript";
import { chatApi, threadsApi } from "@/lib/api/client";
import type { AppUIMessage } from "@/lib/chat/ui-message";
import { convertMessageDtosToUI, mergeEarlierMessages } from "@/lib/converters";
import { completeInteraction, threadSwitchMark } from "@/lib/perf/client-latency";
import { THREADS_QUERY_KEY, threadMessagesQueryKey } from "@/lib/query-keys";
import { getChatForThread, useChatStore } from "@/store/chat-store";
import { useQueryClient } from "@tanstack/react-query";
import type { ModelId } from "@/lib/ai/model-registry";

export function ChatShell({
  threadId,
  isNewThread,
}: {
  /** The thread being viewed. Generated by the server on the home page. */
  threadId: string;
  /**
   * True on the home page, where the id names a conversation that does not
   * exist yet. Passed in rather than inferred from an empty transcript: "no
   * messages yet" and "never had any" look identical and mean different
   * things, and the second must not cost a round trip.
   */
  isNewThread: boolean;
}) {
  const { selectedModel } = useChatStore();
  const queryClient = useQueryClient();

  const transcript = useThreadTranscript({ threadId, isNewThread });

  /**
   * The transcript as it exists in the cache *right now*, read during render.
   *
   * This is the line that makes a warm switch instant. Going through the
   * query's state instead would render once with nothing and once with the
   * messages, and the frame in between is the skeleton flash this phase exists
   * to remove. Recomputed only when the thread changes, because within a
   * thread the chat instance is the source of truth from here on.
   */
  const seedMessages = useMemo(
    () => convertMessageDtosToUI(readCachedWindow(queryClient, threadId)?.messages ?? []),
    [queryClient, threadId],
  );

  // One instance per thread, seeded once. Nothing here overwrites `messages`
  // unconditionally: the shell used to `setMessages(serverMessages)` on every
  // navigation, which raced a running stream and could erase tokens that had
  // already arrived. See `store/chat-store.ts`.
  const chatInstance = useMemo(
    () => getChatForThread(threadId, seedMessages),
    [threadId, seedMessages],
  );

  const { messages, setMessages, sendMessage, status, error, regenerate, stop, clearError } =
    useChat<AppUIMessage>({
      chat: chatInstance,
      // Reattaches to an answer that was still being written when the page was
      // last closed. Answers 204 and does nothing when there is none, which is
      // almost every load.
      resume: true,
    });

  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [isLoadingEarlier, setIsLoadingEarlier] = useState(false);
  const [starterPrompt, setStarterPrompt] = useState({ text: "", version: 0 });
  const composerRef = useRef<HTMLDivElement | null>(null);
  const loadingEarlierRef = useRef(false);
  const previousStatusRef = useRef<ChatStatus>(status);
  const earlierLoadedRef = useRef(false);

  useChatViewport(composerRef);

  /**
   * Closes the thread-switch timer opened by whatever navigated here.
   *
   * "Warm" is decided by whether this thread's first render already had its
   * messages — which is exactly the thing the budget is about. Deciding it
   * here rather than at the click is what keeps the two numbers honest: the
   * sidebar can believe a thread is cached and be wrong, this cannot.
   */
  useEffect(() => {
    completeInteraction(
      threadSwitchMark(threadId),
      seedMessages.length > 0 ? "chat_thread_switch_warm_p95" : "chat_thread_switch_cold_p95",
    );
  }, [seedMessages.length, threadId]);

  // A fresh thread starts a fresh pagination cursor; the window's own cursor
  // takes over below once it is known.
  useEffect(() => {
    earlierLoadedRef.current = false;
    setNextCursor(null);
  }, [threadId]);

  /**
   * Adopts the server's window when it has more than the instance does.
   *
   * Three cases reach this, and the count comparison covers all three without
   * needing to tell them apart: a cold thread whose instance was created
   * empty, a thread whose instance was evicted from the bounded chat cache,
   * and a cached transcript that another device has since added to. The
   * comparison is also what makes it safe — it can only ever add history, so
   * it cannot truncate a live answer or undo a stopped one.
   *
   * Never while a turn is in flight, and never after "load earlier" has pulled
   * in history the window does not contain.
   */
  useEffect(() => {
    const serverWindow = transcript.window;
    if (serverWindow === null || earlierLoadedRef.current) return;
    if (status === "streaming" || status === "submitted") return;

    setNextCursor(serverWindow.nextCursor);
    if (serverWindow.messages.length <= messages.length) return;

    setMessages(convertMessageDtosToUI(serverWindow.messages));
  }, [messages.length, setMessages, status, transcript.window]);

  useEffect(() => {
    if (!error) return;
    toast.error(error.message || "Something went wrong", { id: "chat-send-error" });
  }, [error]);

  useEffect(() => {
    if (transcript.error === null) return;
    toast.error(transcript.error.message || "Could not load this conversation", {
      id: "chat-transcript-error",
    });
  }, [transcript.error]);

  /**
   * A finished turn has changed the sidebar — the title is generated from the
   * first exchange, behind the response, and the ordering has certainly moved
   * — and has added messages this thread's cached window does not have.
   * Invalidating both on the streaming → idle edge is what makes the generated
   * title appear without a reload, and what keeps the persisted transcript
   * from being one turn behind the next time this thread is opened.
   */
  useEffect(() => {
    const wasStreaming =
      previousStatusRef.current === "streaming" || previousStatusRef.current === "submitted";
    previousStatusRef.current = status;
    if (!wasStreaming || status === "streaming" || status === "submitted") return;

    void queryClient.invalidateQueries({ queryKey: THREADS_QUERY_KEY });
    void queryClient.invalidateQueries({ queryKey: threadMessagesQueryKey(threadId) });
  }, [queryClient, status, threadId]);

  const liveStatus: ChatStatus = status;
  const visibleStatus = useChatVisibleStatus({ status: liveStatus, error, messages });
  const isEmpty = messages.length === 0;

  /**
   * Redoes the last answer, optionally on a different model.
   *
   * `regenerate` re-posts with `regenerate: true`, which tells the server to
   * replace the superseded answer rather than append beside it — in the same
   * transaction that writes the new one, so the thread is never briefly
   * showing two answers to one question.
   */
  const handleRegenerate = useCallback(
    (modelId?: ModelId) => {
      // Nothing to redo. `regenerate()` targets the last message by index and
      // throws on an empty list, which the status bar's Retry could reach after
      // a turn failed before the first message was ever rendered.
      if (messages.length === 0) return;

      clearError();
      void regenerate({
        body: { selectedModel: modelId ?? selectedModel, regenerate: true, attachmentIds: [] },
      });
    },
    [clearError, messages.length, regenerate, selectedModel],
  );

  const handleRetry = useCallback(() => {
    handleRegenerate();
  }, [handleRegenerate]);

  /**
   * Stops the answer, on both sides.
   *
   * The local `stop()` is what makes the UI respond at once; the request is
   * what actually ends the turn, because the server cannot tell an abort from
   * a refresh and must not guess. The local call goes first so the button
   * never feels like it did nothing.
   */
  const handleStop = useCallback(async () => {
    // `stop()` resolves once the local request is torn down; nothing depends on
    // that having finished before the server is told, so it is not awaited.
    void stop();
    try {
      await chatApi.stopStream(threadId);
    } catch (stopError) {
      toast.error(stopError instanceof Error ? stopError.message : "Could not stop the response.");
    }
  }, [stop, threadId]);

  const handlePromptSelect = useCallback((prompt: string) => {
    setStarterPrompt((current) => ({ text: prompt, version: current.version + 1 }));
  }, []);

  const loadEarlier = useCallback(async () => {
    if (
      !nextCursor ||
      loadingEarlierRef.current ||
      status === "submitted" ||
      status === "streaming"
    )
      return;

    loadingEarlierRef.current = true;
    setIsLoadingEarlier(true);
    try {
      const page = await threadsApi.messages(threadId, {
        cursor: nextCursor,
        limit: TRANSCRIPT_WINDOW_SIZE,
      });
      const earlier = convertMessageDtosToUI(page.messages);
      setMessages((current) => mergeEarlierMessages(current, earlier));
      setNextCursor(page.nextCursor);
      // From here the instance holds more than the cached window does, so the
      // adoption effect above must stop comparing the two.
      earlierLoadedRef.current = true;
    } catch (loadError) {
      toast.error(
        loadError instanceof Error ? loadError.message : "Could not load earlier messages",
      );
    } finally {
      loadingEarlierRef.current = false;
      setIsLoadingEarlier(false);
    }
  }, [nextCursor, setMessages, status, threadId]);

  const composer = (
    <ChatComposer
      sendMessage={sendMessage}
      stop={handleStop}
      status={liveStatus}
      visibleStatus={visibleStatus}
      threadId={threadId}
      isNewThread={isNewThread}
      initialInput={starterPrompt.text}
      initialInputVersion={starterPrompt.version}
      containerRef={composerRef}
      onRetry={handleRetry}
    />
  );

  /*
    A thread whose history is still arriving is not an empty thread.

    Rendering the empty state for it and then replacing it with a transcript
    is the layout shift Phase L item 5 is about — two different containers,
    two different max widths, two different corner radii, one after the other.
    So "loading" takes the *transcript's* geometry and fills in, and only a
    genuinely empty conversation gets the starter prompts.
  */
  const isLoadingTranscript = isEmpty && transcript.isPending;

  if (isEmpty && !isLoadingTranscript) {
    return (
      <div className="flex h-dvh min-h-0 flex-1 flex-col overflow-hidden px-2 py-3 [height:var(--chat-viewport-height,100dvh)] sm:px-6 sm:py-5">
        <div className="relative mx-auto flex min-h-0 w-full max-w-5xl flex-1 flex-col items-center justify-end overflow-hidden rounded-5xl border border-hairline bg-surface-sunken/35 px-4 pb-0 shadow-elevation-xl inset-shadow-highlight backdrop-blur-glass-heavy md:justify-center md:px-8">
          <div
            className="brand-rule pointer-events-none absolute inset-x-8 top-0 h-px"
            aria-hidden
          />
          <ChatAnnouncer status={visibleStatus} messages={messages} />
          <ChatEmptyState onPromptSelect={handlePromptSelect} />
          <div className="w-full">{composer}</div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-dvh min-h-0 flex-1 flex-col overflow-hidden px-2 pt-2 [height:var(--chat-viewport-height,100dvh)] sm:px-5 sm:pt-4">
      <div className="relative mx-auto flex min-h-0 w-full max-w-6xl flex-1 flex-col items-center overflow-hidden rounded-t-5xl border-x border-t border-hairline bg-surface-sunken/30 shadow-elevation-xl inset-shadow-highlight backdrop-blur-glass-heavy">
        <div
          className="brand-rule pointer-events-none absolute inset-x-10 top-0 h-px"
          aria-hidden
        />
        <ChatAnnouncer status={visibleStatus} messages={messages} />
        {/*
          A thread page had no heading at all.

          The empty state carries the only `<h1>` in the workspace, so a page
          with a transcript — the state a user is in for all but the first
          moment of a conversation — failed `page-has-heading-one`, and a
          screen-reader user pressing `1` landed nowhere. Visually hidden
          because the design deliberately has no title bar; the conversation's
          own title is already the document title, set by `ThreadDocumentTitle`.
        */}
        <h1 className="sr-only">Conversation</h1>
        <section className="flex min-h-0 w-full flex-1 flex-col overflow-hidden">
          {isLoadingTranscript ? (
            <div className="min-h-0 flex-1 overflow-hidden" role="status">
              <TranscriptPlaceholder />
              <span className="sr-only">Loading conversation…</span>
            </div>
          ) : (
            <ChatMessageList
              messages={messages}
              status={liveStatus}
              threadId={threadId}
              hasEarlierMessages={nextCursor !== null}
              isLoadingEarlier={isLoadingEarlier}
              onLoadEarlier={loadEarlier}
              onRegenerate={handleRegenerate}
            />
          )}
          {composer}
        </section>
      </div>
    </div>
  );
}

/**
 * The shape of a conversation, while its first window is on its way.
 *
 * Only reachable on a cold thread — one this browser has never opened — since
 * a revisited thread renders its real messages on the first frame. It mirrors
 * the transcript's rhythm inside the transcript's own container, so the swap
 * to real content changes text and nothing else.
 */
function TranscriptPlaceholder() {
  const rows: ReadonlyArray<{ readonly align: "start" | "end"; readonly widths: string[] }> = [
    { align: "end", widths: ["w-2/5"] },
    { align: "start", widths: ["w-full", "w-11/12", "w-3/4"] },
    { align: "end", widths: ["w-1/3"] },
    { align: "start", widths: ["w-full", "w-4/5"] },
  ];

  return (
    <div className="mx-auto flex w-full max-w-4xl flex-col gap-6 px-3 py-6 sm:px-5" aria-hidden>
      {rows.map((row, rowIndex) => (
        <div
          key={rowIndex}
          className={`flex flex-col gap-2 ${row.align === "end" ? "items-end" : "items-start"}`}
        >
          {row.widths.map((width, index) => (
            <Skeleton key={index} className={`h-4 ${width} max-w-full bg-glass`} />
          ))}
        </div>
      ))}
    </div>
  );
}
